### ISSUE TITLE
ImportError: cannot import name 'pep425tags'

### ISSUE THREAD

**Issue by juju4** [google/rekall#543]
Since past week, in my ansible role for rekall, I have few test travis failing validation on
https://travis-ci.org/github/juju4/ansible-rekall/jobs/718677473#L5236
```
         4) Command "/usr/local/bin/rekall --version" stderr is expected not to match /Error/
            Failure/Error: its(:stderr) { should_not match /Error/ }
              expected "Traceback (most recent call last):\n  File \"/usr/local/bin/rekall\", line 5, in <module>\n    from ...e 70, in <module>\n    from wheel import pep425tags\nImportError: cannot import name 'pep425tags'\n" not to match /Error/
              Diff:
              @@ -1,14 +1,27 @@
              -/Error/
              +Traceback (most recent call last):
              +  File "/usr/local/bin/rekall", line 5, in <module>
              +    from rekall.rekal import main
              +  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/rekal.py", line 41, in <module>
              +    entry_point.load()
              +  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
              +    return self.resolve()
              +  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
              +    module = __import__(self.module_name, fromlist=['__name__'], level=0)
              +  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall_agent/__init__.py", line 3, in <module>
              +    from rekall_agent import agent
              +  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall_agent/agent.py", line 70, in <module>
              +    from wheel import pep425tags
              +ImportError: cannot import name 'pep425tags'
```
This affects only centos8 (python 3.6.8) and ubuntu18.04 (python 3.6.9) and seems related to the use of some pip internals
https://github.com/pypa/pip/issues/5284
https://github.com/buildout/buildout.wheel/issues/18
it works on centos7 (3.6.8) and ubuntu20.04 (3.8.2)
same result between latest pip release and when using git HEAD

corresponding code seems 3 years old which seems to match above assessment
https://github.com/google/rekall/blame/8db49aa92439d4787023c1ea37561b6903cabf9b/rekall-agent/rekall_agent/agent.py#L69

any advices to fix this?

Thanks

**Comment by pag-crypto** [comment]
I am also seeing this issue when I try to run rekall. I am running in a virtual environment on Ubuntu 16.04 LTS with
`Python 3.5.2 (default, Jul 17 2020, 14:04:10)
[GCC 5.4.0 20160609] on linux`

**Comment by scudette** [comment]
It seems to be a breaking change with pip

https://github.com/buildout/buildout.wheel/issues/18

But the backtrace indicates that it's being used somewhere inside
setuptools (ie rekall doesn't actually use it directly anyway).

 This is probably just a side effect of the terrible state of python
packaging. It may be improved by upgrading setup tools or pip or something
else...

Thanks
Mike

**Comment by scudette** [comment]
Oh no sorry, I read it wrong....

It is used by rekall-agent. You should just remove the import for it and
the dependency in the setup.py. it is no longer useful.

**Comment by JustMyGithub** [comment]
I think I had the same issue on windows build. Solved it by sticking wheels to 0.34.2

afaik wheels moved functions that were not intended to be called from outside the module
