### ISSUE TITLE
Rekall installation failed on Debian Buster (Python 3.7)

### ISSUE THREAD

**Issue by mtarral** [google/rekall#510]
Hi,

It seems that Rekall has been broken since a while now, on newer versions of Python.

Debian Buster is the new stable now, and it upgraded Python 3.7.

Unfortunately, this breaks Rekall, as multiple dependencies don't compile with Python 3.7 headers:
- `PyYAML`
- `acora`
- `fastchunking`

~~~
Building wheel for PyYAML (setup.py) ... error
...
  In file included from ext/_yaml.h:2,                                                                                                                                                  
                   from ext/_yaml.c:271:                                                                                                                                                
  /usr/include/yaml.h:1370:30: note: expected ‘int (*)(void *, unsigned char *, size_t,  size_t *)’ {aka ‘int (*)(void *, unsigned char *, long unsigned int,  long unsigned int *)’} but argument is of type ‘int (*)(void *, char *, size_t,  size_t *)’ {aka ‘int (*)(void *, char *, long unsigned int,  long unsigned int *)’}                                             
           yaml_read_handler_t *handler, void *data);                                                                                                                                   
           ~~~~~~~~~~~~~~~~~~~~~^~~~~~~ 
...
ERROR: Failed building wheel for PyYAML
Running setup.py clean for PyYAML
Building wheel for acora (setup.py) ... error
...
acora/_cacora.c: In function ‘__Pyx_ExceptionSave’:                                                                                                                                   
  acora/_cacora.c:14708:21: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?                                                       
       *type = tstate->exc_type;                                                                                                                                                        
                       ^~~~~~~~                                                                                                                                                         
                       curexc_type        
 ...              
ERROR: Failed building wheel for acora
Running setup.py clean for acora
Building wheel for fastchunking (setup.py) ... error
...
x86_64-linux-gnu-gcc: fatal error: no input files
...
ERROR: Failed building wheel for fastchunking
Running setup.py clean for fastchunking
Failed to build PyYAML acora fastchunking
~~~

@scudette is it possible to fix these dependencies in Rekall ? either upgrading them or reporting a bug upstream ?

Also can I rely on Rekall in the future, is it still maintained ?
Is has been broken since a while now

related:
- #488 
- #474 
- #447 
- #433 

Thanks.

**Comment by scudette** [comment]
You are right it is not very maintained at the moment :-(

But it does actually build on current versions. You need to:

* increase the version of acroa to 2.2
```
diff --git a/rekall-core/setup.py b/rekall-core/setup.py
index dd7c83d9..9a719584 100755
--- a/rekall-core/setup.py
+++ b/rekall-core/setup.py
@@ -53,7 +53,7 @@ def find_data_files(source):
 # when external packages are upgraded in an incompatible way.
 install_requires = [
     'PyYAML==3.12',
-    'acora==2.0',
+    'acora==2.2',
     'arrow==0.10.0',
     'artifacts==20170909',
     'future',
```
Then you build from source as normal:
```
$ pip install -e rekall-lib rekall-core .
$ pip install pyaff4==0.26 future==0.16.0
```

You can then override dependencies back to older versions.

Unfortunately python is not easy to work with when it comes to packaging or dependencies and I guess some of the constraints we made were too loose in setup.py so newer versions are accepted which broke the build.

I probably should fix the dependencies and make another pypi release but it is really going to mainly tightening up the dependencies so older versions are used rather than update to the new version (at least it would build cleanly).

Happily I dont do any python these days !!!

**Comment by mtarral** [comment]
I pulled from rekall master, and I upgraded acora in `setup.py`

> Then you build from source as normal:

> $ pip install -e rekall-lib rekall-core .

I have the same issues, with `PyYAML`, `acora`.

However, If I install them manually `pip install acora==2.2`, it works, but it doesn't try to compile any C extension.

When I they get installed via `rekall-core`, it fails.
Is it absolutely necessary to compile these C extensions ?

Thanks.

**Comment by scudette** [comment]
Do you have python3-all-dev installed? it should bring in python headers etc. needed for building c extensions. I am pretty sure PyYML C extension is optional though.

With python trying to install by hand will satisfy the dependency in the setup.py.

You should be able to upgrade dependencies in setup.py - most packages like acora and PyYAML should have similar API going forward.  I would just make sure the latest package of whatever break actually can build then change setup.py to use it and watch for breakage (if the new version is not backward compatible).

It had been reported before that pyaff4 is not properly backwards compatible so we need to pin it at 0.26

**Comment by obilodeau** [comment]
I had to workaround the rekall install again today for a class I'm teaching. This gist is what I give to students: https://gist.github.com/obilodeau/d0d8a7e2cf4e476463e8b08c309d8484

**Comment by siftuser** [comment]
@obilodeau thanks for [link](https://gist.github.com/obilodeau/d0d8a7e2cf4e476463e8b08c309d8484)! It worked until the last command. Errors out 
`./venv/bin/rekall: command not found`

**Comment by obilodeau** [comment]
If you activated the `venv` (`source venv/bin/activate`) you don't need to prefix `rekall` at all, just:

```
$ rekall
```

or

```
$ rekal
```

should work. If it doesn't, it means something went wrong installing the pip packages.

**Comment by siftuser** [comment]
thanks @obilodeau ! tried that ... throws some random error. As you mentioned, due to something else, but the installation went successful without errors

**Comment by q2dg** [comment]
Well...last release was from two years ago...it's time to go to any other place

**Comment by aoshiken** [comment]
Take a look to the PR #521
